In [3]:
import pandas as pd
import matplotlib.pyplot as plt

bookings_raw = pd.read_csv("hotel_bookings_final_project.csv")

bookings_raw.info()

bookings_raw.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   hotel                        1000 non-null   object
 1   is_canceled                  1000 non-null   int64
 2   lead_time                    1000 non-null   int64
 3   arrival_date_year            1000 non-null   int64
 4   arrival_date_month           1000 non-null   object
 5   arrival_date_day_of_month    1000 non-null   int64
 6   stays_in_weekend_nights      1000 non-null   int64
 7   stays_in_week_nights         1000 non-null   int64
 8   adults                       1000 non-null   int64
 9   children                     1000 non-null   int64
 10  babies                       1000 non-null   int64
 11  country                      998 non-null    object
 12  market_segment               1000 non-null   object
 13  deposit_type                 1000 non-null   object
 14  customer_type                1000 non-null   object
 15  average_daily_rate           1000 non-null   float64
 16  is_repeated_guest            1000 non-null   int64
 17  booking_changes              1000 non-null   int64
 18  required_car_parking_spaces  1000 non-null   int64
 19  total_of_special_requests    1000 non-null   int64
dtypes: float64(1), int64(13), object(6)
memory usage: 156.4+ KB

,is_canceled,lead_time,arrival_date_year,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,average_daily_rate,is_repeated_guest,booking_changes,required_car_parking_spaces,total_of_special_requests
count,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.36600,105.065000,2016.134000,16.13300,0.924000,2.525000,1.8630,0.109000,0.009000,101.210870,0.032000,0.240000,0.060000,0.593000
std,0.48195,106.445476,0.701809,8.96134,0.954534,1.802394,0.5334,0.404082,0.094488,45.716531,0.176088,0.674429,0.237606,0.799994
min,0.00000,0.000000,2015.000000,1.00000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,19.000000,2016.000000,8.00000,0.000000,1.000000,2.0000,0.000000,0.000000,68.575000,0.000000,0.000000,0.000000,0.000000
50%,0.00000,69.500000,2016.000000,16.00000,1.000000,2.000000,2.0000,0.000000,0.000000,94.500000,0.000000,0.000000,0.000000,0.000000
75%,1.00000,157.000000,2017.000000,24.00000,2.000000,3.000000,2.0000,0.000000,0.000000,125.000000,0.000000,0.000000,0.000000,1.000000
max,1.00000,542.000000,2017.000000,31.00000,8.000000,20.000000,6.0000,3.000000,1.000000,304.000000,1.000000,7.000000,1.000000,5.000000

In [4]:
bookings_raw.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,country,market_segment,deposit_type,customer_type,average_daily_rate,is_repeated_guest,booking_changes,required_car_parking_spaces,total_of_special_requests
0,City Hotel,1,1,2015,September,30,0,2,1,0,0,PRT,Offline TA/TO,Non Refund,Transient,98.10,1,0,0,0
1,Resort Hotel,1,19,2016,March,19,2,4,2,0,0,PRT,Online TA,No Deposit,Transient,70.17,0,0,0,1
2,Resort Hotel,0,9,2017,August,1,0,4,2,0,0,ESP,Online TA,No Deposit,Transient,193.40,0,0,0,1
3,Resort Hotel,0,110,2016,November,11,0,1,2,0,0,BRA,Online TA,No Deposit,Transient,36.24,0,2,1,0
4,City Hotel,0,329,2017,July,27,0,2,2,0,0,GBR,Online TA,No Deposit,Transient,89.10,0,0,0,1

In [19]:
print("Duplicate rows:", bookings_raw.duplicated().sum())

print("\nMissing values:")
print(bookings_raw.isna().sum())

print("\nRegion labels:", sorted(bookings_raw["hotel"].dropna().unique()))

print("product_category labels:", sorted(bookings_raw["arrival_date_month"].dropna().unique()))

print("customer_type labels:", sorted(bookings_raw["country"].dropna().unique()))

print("returned labels:", sorted(bookings_raw["market_segment"].dropna().unique()))

print("returned labels:", sorted(bookings_raw["deposit_type"].dropna().unique()))

print("returned labels:", sorted(bookings_raw["customer_type"].dropna().unique()))

print("returned labels:", sorted(bookings_raw["arrival_date_month"].dropna().unique()))

invalid_cancelations = bookings_raw.loc[
    bookings_raw["is_canceled"].notna() &
    ~bookings_raw["is_canceled"].isin([0, 1])
]

invalid_lead_times = bookings_raw.loc[
    bookings_raw["lead_time"].notna() &
    ~bookings_raw["lead_time"] < 0
]

invalid_arrival_date_day_of_month = bookings_raw.loc[
    bookings_raw["arrival_date_day_of_month"].notna() &
    ~bookings_raw["arrival_date_day_of_month"].between(1, 31)
]

invalid_stays_in_weekend_nights = bookings_raw.loc[
    bookings_raw["stays_in_weekend_nights"].notna() &
    ~bookings_raw["stays_in_weekend_nights"].between(0, 2)
]

invalid_stays_in_week_nights = bookings_raw.loc[
    bookings_raw["stays_in_week_nights"].notna() &
    ~bookings_raw["stays_in_week_nights"].between(0, 5)
]

invalid_repeated_guests = bookings_raw.loc[
    bookings_raw["is_repeated_guest"].notna() &
    ~bookings_raw["is_repeated_guest"].isin([0, 1])
]

invalid_cancelations["is_canceled"]
invalid_lead_times["lead_time"]
invalid_arrival_date_day_of_month["arrival_date_day_of_month"]
invalid_stays_in_weekend_nights["stays_in_weekend_nights"]
invalid_stays_in_week_nights["stays_in_week_nights"]
invalid_repeated_guests["is_repeated_guest"]

Duplicate rows: 26

Missing values:
hotel                          0
is_canceled                    0
lead_time                      0
arrival_date_year              0
arrival_date_month             0
arrival_date_day_of_month      0
stays_in_weekend_nights        0
stays_in_week_nights           0
adults                         0
children                       0
babies                         0
country                        2
market_segment                 0
deposit_type                   0
customer_type                  0
average_daily_rate             0
is_repeated_guest              0
booking_changes                0
required_car_parking_spaces    0
total_of_special_requests      0
dtype: int64

Region labels: ['City Hotel', 'Resort Hotel']
product_category labels: ['April', 'August', 'December', 'February', 'January', 'July', 'June', 'March', 'May', 'November', 'October', 'September']
customer_type labels: ['AGO', 'ARG', 'ARM', 'AUS', 'AUT', 'BEL', 'BGR', 'BRA', 'CAF', 'CHE', 'CHN', 'CN', 'DEU', 'DNK', 'DZA', 'EGY', 'ESP', 'FIN', 'FRA', 'GBR', 'GIB', 'GRC', 'HRV', 'HUN', 'IND', 'IRL', 'ISL', 'ISR', 'ITA', 'KIR', 'KOR', 'LBY', 'LUX', 'LVA', 'MAR', 'MEX', 'MOZ', 'NLD', 'NOR', 'NZL', 'PER', 'PHL', 'POL', 'PRT', 'ROU', 'RUS', 'SGP', 'SWE', 'TUR', 'TWN', 'UKR', 'USA']
returned labels: ['Complementary', 'Corporate', 'Direct', 'Groups', 'Offline TA/TO', 'Online TA']
returned labels: ['No Deposit', 'Non Refund', 'Refundable']
returned labels: ['Contract', 'Group', 'Transient', 'Transient-Party']
returned labels: ['April', 'August', 'December', 'February', 'January', 'July', 'June', 'March', 'May', 'November', 'October', 'September']

Series([], Name: is_repeated_guest, dtype: int64)

Most of the data values are present and the data values seem to be clean. There are only a couple "country" values missing. Since they would not have a big affect on the result, we can simply fill the values with "unknown".
Although, there are 26 duplicate rows, it does not seem like it will couse any problems, because none of the data values need to be unique.

In [20]:
bookings = bookings_raw

bookings["country"] = bookings["country"].fillna("Unknown")

print("\nMissing values:")
print(bookings.isna().sum())

Missing values:
hotel                          0
is_canceled                    0
lead_time                      0
arrival_date_year              0
arrival_date_month             0
arrival_date_day_of_month      0
stays_in_weekend_nights        0
stays_in_week_nights           0
adults                         0
children                       0
babies                         0
country                        0
market_segment                 0
deposit_type                   0
customer_type                  0
average_daily_rate             0
is_repeated_guest              0
booking_changes                0
required_car_parking_spaces    0
total_of_special_requests      0
dtype: int64